// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WAD_Assignment1.Models;

namespace WAD_Assignment1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210428163757_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WAD_Assignment.Models.Recipe", b =>
                {
                    b.Property<short>("RecipeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<short>("CookingTime")
                        .HasColumnType("smallint");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(46)");

                    b.Property<string>("Ingredient1")
                        .HasColumnType("varchar(54)");

                    b.Property<string>("Ingredient2")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Ingredient3")
                        .HasColumnType("varchar(73)");

                    b.Property<string>("Ingredient4")
                        .HasColumnType("varchar(49)");

                    b.Property<string>("Ingredient5")
                        .HasColumnType("varchar(43)");

                    b.Property<string>("Ingredient6")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ingredient7")
                        .HasColumnType("varchar(56)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Step1")
                        .HasColumnType("varchar(489)");

                    b.Property<string>("Step2")
                        .HasColumnType("varchar(529)");

                    b.Property<string>("Step3")
                        .HasColumnType("varchar(437)");

                    b.Property<string>("Step4")
                        .HasColumnType("varchar(167)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(46)");

                    b.HasKey("RecipeID");

                    b.ToTable("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
